name: quran_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 1.1.0
  lottie: 2.4.0
  get_storage: 2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
  uses-material-design: true

