name: quran_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 1.1.0
  lottie: 2.4.0
  get_storage: 2.1.1
  shimmer: 3.0.0
  geolocator: 9.0.2
  geocoding: 2.1.0
  just_audio: 0.9.34
  sqflite: 2.2.8+4
  path_provider: 2.0.15
  scroll_to_index: 3.0.1
  flutter_tts: 3.7.0
  permission_handler: 10.4.3
  flutter_qiblah: 2.2.0
  intl: 0.18.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 23

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
  uses-material-design: true

